### ISSUE TITLE
Missing elements in the OpenMapTiles Vector Tile Schema 

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/VectorMap#29]
#### Critical
- [x] Fields in `transportation` layer
   - [x] colour
   - [x] bicycle [yes, no, designated]
   - [x] mtb:scale
   - [x] Split `colour` tags with `;` into `colour` and `colour2`
- [x] New `trail` layer for relation members
   - route: hiking, mtb, bicycle
   - network
   - osmc:symbol
   - colour of member
- [x] New `barrier` layer
   - barrier: block, debris, kissing_gate, cattle_grid, hampshire_gate
   - access
   - motor_vehicle
- [x] New `linear_barrier` layer
   - [x] barrier: fence, wall, city_wall
   - [x] barrier: yes (for the separation barrier)
   - [x] <del>route = fence relation<del>
- [x] Tracks and paths at lower zoom levels than 14 (or you'll have to zoom in to plan long desert rides)

#### Important
 - [x] aerialway (other than the existing cable car) to show ski lifts at the Hermon
 - [x] landuse=recreation_ground, sport=mtb
- [x] `water*` layers
  - [X] Intermittent tag for water
- [x] Add subclasses to `poi` layer
  - [x] amenity: drinking_water, parking
  - [x] natural: spring, water_hole
  - [x] man_made: storage_tank, cistern, water_well
  - [x] historic: memorial
  - [x] natural: pond
- [x] `transportation` layer
   - [x] tracktype
   - [x] Include paved tracks in the `minor` class 
   - [x] Include unpaved minor roads in the the `track` class
- [x] `name_he` similar to `name_en` and `name_de`
- [x] Add `name`s to boundaries (See IsraelHikingMap/openmaptiles#16)
- [x] Non-OSM vector sources
  - [x] Contours (See IsraelHikingMap/openmaptiles#7)
  - [x] Israeli grid (See IsraelHikingMap/openmaptiles#14)
- [x] `landuse` layer (artificial characteristics)
  - [x] nature_reserve (only national parks included in parks) IsraelHikingMap/openmaptiles#19
  - [x] quarry
  - [x] military bases
- [x] `landcover` layer (natural characteristics)
  - [x] natural: scrub
- [x] New layer for natural linear features: ridge, valley, cliff
- [x]  `mountain_peak` layer: Add peaks with names, but without elevation
- [x]  Waterways at lower zooms, say 11 (now at 13)
- [x] `transportation_name` layer
   - [x] `mtb:name`
#### Nice to have
- [x] `poi` layer
  - [x] natural:  cave, tree, flowers 
  - [x] historic=archaeological site
  - [x] elevation as a field in points beyond mountain-peaks (e.g. viewpoints)
  - [x] man_made: antenna, tower
     - identify antenna using `tower:type=communication`
  - [x] waterway=waterfall
  - [x] tomb=hypogeum
  - [x] information=guidepost
  - [x] man_made: water_tower
  - [x] `landuse`: `military`, `quarry`, `industrial`, `commercial`, `retail` 
- [x] `power` layer
  - [x] power line
  - [x] power tower
- [x] Merge national and regional trail segments by name
- [x] Merge rivers and streams by name
- [x]  leisure=swimming_pool in `water` layer
- [x] Add to `place` layer
  - [x] place=farm
- [x] Add to `landuse` layer (artificial characteristics)
  - [x] farmyard, farmland, construction, brownfield
  - [x] power: substation, sub_station, plant
  - [x] Some national parks not imported (e.g. Meggido)
  - [x] man_made:waterworks, wastewater_plant
- [x] Streets with moderated traffic (speed < 30kmh)

#### Can be removed
See #33

**Comment by zstadler** [comment]
Recent updates:
- Added `mtb:name`, `mtb:name:he`, `mtb:name:en` fields in `transportation_name` layer
- Added `landuse=recreation_ground` to `poi` layer
- Added `leisure=swimming_pool` to `water` layer

**Comment by zstadler** [comment]
@valleyofdawn,
Please note that instead of

> - [ ] Add to `place` layer as `farm` class
>   - [ ] place=farm
>   - [ ] landuse=farmyard 
>   - [ ] landuse=farmland

The change will be

> - [ ] Add to `place` layer
>   - [ ] place=farm
> - [ ] Add to `landuse` layer
>   - [ ] landuse=farmyard 
>   - [ ] landuse=farmland

**Comment by zstadler** [comment]
Recent update:
- Add to `landuse` layer
  - `farmyard`
  - `farmland`
  - `construction`
  - `brownfield`
  - `substation`
  - `sub_station`
  - `plant`
  - `waterworks`
  - `wastewater_plant`
- Remove from `landuse` layer
  - `bus_station`
  - `school`
  - `kindergarten`
- Add to `poi` layer
  - `recreation_ground `
  - `military`
  - `industrial`
  - `commercial`
  - `retail`
  - `quarry`
- Add to `place` layer
  - `farm`
- Add to `landcover` layer
  - `farmyard`

**Comment by zstadler** [comment]
Recent update:
- Add to `transportation` layer
  - `maxspeed`
  - `mtb:oneway`

**Comment by zstadler** [comment]
- The `linear_barrier` layer was renamed `ihm_lines`.
- Power lines and towers were added to the `ihm_lines` layer.
- The existing styles were updated to use the `ihm_lines` layer - https://github.com/IsraelHikingMap/VectorMap/commit/21895e5662b2ef8322689a950525aecd088c7fbd.
